- name: Launch reverse proxy (NGINX)
  docker_container:
    name: my_proxy
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    networks:
      - name: my_app_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
