- name: Launch database container
  docker_container:
    name: my_database
    image: postgres:15
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    networks:
      - name: my_app_network
    volumes:
      - db_data:/var/lib/postgresql/data
  vars:
    ansible_python_interpreter: /usr/bin/python3
