
- hosts: all
  gather_facts: true
  become: true

  vars:
    arch_map:
      x86_64: amd64
      aarch64: arm64
      armv7l: armhf
    docker_arch: "{{ arch_map[ansible_architecture] | default('amd64') }}"
    docker_distro: "{{ (ansible_facts.os_family == 'Debian') | ternary('debian','ubuntu') }}"
    docker_codename: "{{ ansible_facts.distribution_release }}"

  tasks:
    - name: Install prereqs
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: "https://download.docker.com/linux/{{ docker_distro }}/gpg"
        state: present

    - name: Ensure wrong repo file absent
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch={{ docker_arch }}] https://download.docker.com/linux/{{ docker_distro }} {{ docker_codename }} stable"
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
